Feat/#9 business license
BirthdayCafe/Birca_Backend pull request #18
Opened 2024-02-04 14:15 UTC by CMHyuk

## 🌍 이슈 번호
closed https://github.com/BirthdayCafe/Birca_Backend/issues/9

## 📝 구현 내용
* 사업자등록증 스캔 기능 구현  
* 사업자등록증 진위여부 파악 기능 구현  
* 사업자등록증 저장 기능 구현

## 🍀 확인해야 할 부분
### **application 패키지에는 세부 기술이 들어가지 않도록 하기**

피드백해 주신 대로 세부 기술은 infrastrcuture 패키지에 구현을 했는데, 확실히 테스트하기 쉬워졌습니다! 제가 구현한 방식이 의도에 맞게 한 건지 확인해 주시면 감사하겠습니다!

### **사업자등록증 진위 여부 파악**

저번 피드백해 주셨을 때 검증을 문자열(`국세청에 등록되지 않은 사업자등록번호입니다.`)이 아닌 상태 코드로 판별하면 좋을 것 같다고 하셨는데, 상태 코드는 따로 없고 문자열로만 응답이 와서 상수로 처리했습니다.

### **OCR 요청 횟수 검증**

일단 임시로 OCR 최대 요청 횟수는 3회라고 가정하고 구현했습니다.
Member 테이블에 ocrRequestCount 컬럼 추가 후 검증 vs 메모리에 요청 횟수 검증
처음에 컬럼을 추가해서 OCR 요청 횟수를 검증하려고 했지만, 요청 횟수를 카운트하려고 스키마를 변경하고 db에 요청 카운트를 조회해 검증하는 방식이 효율적인지 의문이 들었습니다. 메모리에 저장하면 스키마 변경 없이 간편하고 요청 처리가 빠를 것이라고 생각해서 후자를 택했는데 ****둘 중 어느 것이 적절한 선택일까요?

++이외에 정말 사소한 거라도 수정할 부분 있으면 말씀해 주세요!

2024-02-06 06:39 UTC, CMHyuk commented
@ldk980130   

아직 사업자등록증 횟수 검증은 구현하지 않았고, 먼저 사업자등록증 스캔과 검증 API를 카카오 로그인 코드를 참고해서 다시 구현했습니다!

2024-02-06 07:09 UTC, ldk980130 requested changes
구현 수고하셨습니다! 전체적인 구조는 제가 제안드린대로 잘 구현하신 것 같아요. 테스트 코드도 검증이 필요한 부분을 잘 검증한 것 같습니다.

사소한 부분 리뷰 드렸으니 간단하게 고쳐보면 좋을 것 같아요. 

그리고 파일 끝에 개행을 추가하지 않은 파일이 많이 보이는데 제가 코멘트를 못남긴 부분도 있으니 한 번 전체적으로 체크해 주세요!

++ 테스트가 2개 정도 실패하더라구요. 한 번 확인해주세요!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseService.java
> +    }
dto에서 필요한 필드를 추출하는 코드가 길어서 핵심 비즈니스 로직이 눈에 잘 안들어오는 것 같아요. dto에서 도메인 엔티티로 변환하는 로직을 다른 곳으로 옮겨보면 어떨까요?

간단하게는 dto에서 toEntity() 메서드를 만드는 방법이 있고, 만드는 방식이 복잡할 경우엔 Mapper 클래스를 구현하여 dto <-> 도메인 변환 로직을 위임할 수 있을 것 같아요.

서비스 메서드 로직을 최대한 간결하게 할 수 없을지 고민해보면 좋을 것 같습니다!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseService.java
> +}
`String` 값을 입력 받아서 `BusinessLicenseCode`를 생성하는 메서드네요. `BusinessLicenseCode`에서 `String`을 받는 생성자를 만드는건 어떨까요? 그럼 생성 로직을 도메인에게 위임할 수 있을 것 같아요. 그리고 올바른 형식이 아닐 땐 예외를 발생시키는 코드도 도메인에게 맡길 수 있을 것 같습니다!

``` java
BusinessLicenseCode = code = new BusinessLicenseCode(businessLicenseNumber);
```

++ 그리고 이 클래스 파일 끝에 개행 추가해주세요!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/OcrProvider.java
> +}
사업자등록증을 스캔하는 로직을 인터페이스로 선언한 것 👍

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/VerificationProvider.java
> +}
무엇을 verification하는 클래스라는걸까요? 인터페이스 이름만 봐서는 역할이 분명하지 않은 것 같아요.

그리고 무조건 Provider라는 네이밍을 할 필요는 없습니다. 사업자 등록증의 유효성을 검증하는 인터페이스이므로 더 적절한 이름을 붙여보는건 어떨까요?

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicense.java
> +    private String address;
이건 지금 수정할 필요는 없긴한데 나중에 지도 api를 쓰고 지도에 위치를 찍어주려면 위도 경도 값을 입력해야 하는 것 같더라구요.

나중에는 Address 값 타입으로 변경해서 위도 경도 정보를 포함하도록 2차 개발에선 변경할 필요가 있을 것 같아요.

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicense.java
> +}
개행 추가해주세요!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
> +        return new BusinessLicenseCode(taxOfficeCode, businessTypeCode, serialCode);
정적 팩터리 메서드를 사용하는 것 좋은 것 같습니다!

다만 `BusinessLicenseCode.createBusinessLicenseCode()`는 좀 길지 않을까요? create라는 이름만으로도 충분하다고 생각합니다ㅎㅎ

`BusinessLicenseCode.create()`

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
> +    }
3, 2, 5 같은 매직 넘버를 상수화하면 좋을 것 같아요!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
> +}
개행!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NaverOcrApi.java
> +}
외부 api 통신 코드가 진짜 깔끔해지네요 👍

2024-02-06 07:09 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NaverOcrProvider.java
> +}
개행 추가해주세요~

2024-02-06 07:09 UTC, ldk980130 commented on src/main/resources/application-ci.yml
> +  key: "key"
개행 추가!

2024-02-06 07:09 UTC, ldk980130 commented on src/main/resources/application-local.yml
> +  key: "key"
개행 추가!

2024-02-06 07:09 UTC, ldk980130 commented on src/test/java/com/birca/bircabackend/command/cafe/acceptance/BusinessLicenseAcceptanceTest.java
> +        File businessLicense = new File("src/test/resources/businessLicense.jpg");
테스트용 파일을 준비하는 방법 좋은것 같아요!

2024-02-06 16:23 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseService.java
> +    }
더 최선의 방법이 있을까요?

2024-02-06 16:25 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseStatusVerifier.java
> +}
정확하게는 사업자등록증 상태조회 API라 이처럼 네이밍 했습니다!

2024-02-06 16:27 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
> +    }
도메인으로 위임했고, 검증이 추가됐습니다!

2024-02-06 16:28 UTC, CMHyuk reviewed
로컬에서는 pull 받고 모든 테스트가 통과 되는데 어떤 테스트가 실패하는지 알 수 있을까요?

2024-02-07 02:02 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseService.java
> +    }
이 정도면 충분한 것 같습니다~

2024-02-07 02:28 UTC, ldk980130 approved these changes
이제 테스트 다 돌아갑니다! 이제 merge해도 될 것 같아요. 사업자 등록증은 S3에 저장하는건 다음에 합시다. 수고하셨습니다!

2024-02-07 02:40 UTC, merged