[Feat] 사업자등록증 업로드 횟수 제한 기능
BirthdayCafe/Birca_Backend pull request #27
Opened 2024-02-08 14:46 UTC by CMHyuk

## 🌍 이슈 번호
* closed #22

## 📝 구현 내용
* 사업자등록증 업로드 횟수 제한

## 🍀 확인해야 할 부분
말씀하신대로 인터셉터를 활용해 사업자등록증 업로드 횟수 검증 기능을 구현해봤습니다.
인터셉터를 validation 패키지에 넣어놨는데, 적절한 방식인지 확인해주시면 감사하겠습니다!
조금이라도 걸리는 부분 있으면 말씀해주세요 ~

2024-02-09 07:21 UTC, ldk980130 requested changes
수고하셨습니다! 몇가지 리뷰 남겼으니까 확인해보면 될 것 같아요!

### 생각해 볼만한 것
처음에 제가 `Interceptor` 등으로 구현해보라고 한 것은 기존 사업자등록증 자체의 로직을 최대한 수정하지 않고 횟수 검증 로직을 추가해 보라고 하고 싶어서였어요.

현재 domain 패키지에는 업로드 횟수를 관리하는 history 객체가 포함되어 있고 application 패키지에는 `OcrRequestHistoryService`가 포함되어 있어요.

validation 패키지가 횟수 검증을 책임진다고 했을 때 횟수 검증 로직을 건드려야할 때 domain, application을 안건드리고 validation 패키지만 건드리도록 수정할 수는 없을까요?ㅎㅎ

2024-02-09 07:21 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/OcrRequestLimitConfig.java
> +}
validation 패키지가 업로드 횟수 제한 검증을 하는 패키지라면 이 config 클래스도 그 안에 들어가야 하지 않을까요?

2024-02-09 07:21 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseFacade.java
> +    private final OcrRequestHistoryService ocrRequestHistoryService;
`BusinessLicenseProcessingService`와 `OcrRequestHistoryService`로 `Facade`를 만든 이유가 있을까요?  

(순수한 질문입니다! 의도가 궁금해요~)

2024-02-09 07:21 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/OcrRequestHistory.java
> +    }
`OcrRequestHistory`는 처음 생성될 때 무조건 `uploadCount`가 0이어야해요. 아마 그게 도메인 규칙이겠죠? 이런 규칙과 제약을 담아 생성자를 만드는 건 어떨까요?

2024-02-09 07:21 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/validation/OcrRequestLimitInterceptor.java
> +    }
업로드 횟수를 검증하는 별도의 클래스로 분리하는건 어떨까요?

2024-02-09 07:21 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/validation/OcrRequestLimitInterceptor.java
> +    }
`RequiredLoginInterceptor`가 먼저 작동되고 이 인터셉터가 작동되어야 잘 동작할 것 같아요. 이 부분은 확실하게 토큰 로직이 먼저 작동되고 이 인터셉터가 동작하는 거겠죠? 순서 관리는 어떻게 하고 있을까요?

2024-02-09 08:18 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseFacade.java
> +    private final OcrRequestHistoryService ocrRequestHistoryService;
`Facade` 를 만든 이유는 기존 사업자등록증 로직을 건드리지 않고 싶어서 만들었습니다!

[사업자등록증 횟수 제한]
- 1회 등록까지는 워닝 없음
- 2회 등록부터 워닝텍스트 노출(ex. 현재 등록을 2회 하셨습니다. 앞으로 3회 등록 가능합니다)
- 5회 초과 시 등록 불가  

일단 위 정책에 따라 사업자등록증을 스캔한 정보와 업로드 횟수를 같이 반환해야한다고 생각했습니다.

사업자등록증을 스캔하는 로직은 아시다시피, 스캔한 정보를 담은 `BusinessLicenseOcrResponse` 를 가공해서 `BusinessLicenseInfoResponse`로 반환했습니다.

그런데 업로드 횟수를 같이 반환해야 해서 처음 제가 의도했던 방향은

```
//NaverOcrProvider 클래스
@Override
public BusinessLicenseInfoResponse getBusinessLicenseInfo(MultipartFile businessLicense) {
        BusinessLicenseOcrRequest request = createRequestBody(businessLicense);
        ResponseEntity<BusinessLicenseOcrResponse> response = naverOcrApi.performBusinessLicenseOcr(request, secretKey);
        validateResponse(response);
        return BusinessLicenseInfoResponse.from(response.getBody());
    }
```

`NaverOcrProvider`에서 스캔한 정보를 가공한 dto `BusinessLicenseInfoResponse` 를 반환하는 것이 아닌 가공하지 않은  `BusinessLicenseOcrResponse` 로 반환 후 `BusinessLicenseProcessingService` 에서 스캔한 정보를 가공하고 `OcrRequestHistoryService` 의 `incrementUploadCount`  를 호출해 업로드 횟수를 합쳐서 반환하려고 했습니다. 

하지만 반환 타입이 변경 돼 스펙이 바뀌어서, 테스트 코드도 모두 변경해야했습니다.

번거로운 과정이라 생각해 사업자등록증 정보 + 업로드 횟수를 담은 dto를 하나 추가해, `Facade` 에서 스캔한 정보 + 업로드 횟수를 담은 정보를 반환하도록 구현했습니다! 그리고 컨트롤러에서도 Facade만 호출하면 돼서 더 깔끔해지지 않을까? 라는 생각도 있었습니다 ~

더 좋은 방법이 있을까요?

만약 제가 구현한 방식이 문제가 없다면 
```
@PostMapping("/v1/cafes/apply")
    @RequiredLogin
    public ResponseEntity<Void> saveBusinessLicense(LoginMember loginMember,
                                                    @ModelAttribute BusinessLicenseCreateRequest request) {
        businessLicenseProcessingService.verifyBusinessLicenseStatus(request.businessLicenseNumber());
        businessLicenseService.saveBusinessLicense(loginMember, request);
        return ResponseEntity.ok().build();
    }
```
사업자등록증 상태조회 로직과 저장하는 로직도 'Facade'에  넣는 게 좋을까요?

2024-02-09 08:23 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/cafe/validation/OcrRequestLimitInterceptor.java
> +    }
~~~
@Override
public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(requiredLoginInterceptor)
                .order(1);
}

@Override
public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(ocrRequestLimitInterceptor)
                .order(2);
}
~~~

위처럼 order 속성을 통해 순서 관리를 할 수 있는 것으로 알고 있습니다.
정확한 이유는 모르겠지만 이렇게 안 하고 로그를 찍어봤는데, `RequiredLoginInterceptor`가 먼저 동작이 됐고 테스트 코드도 모두 통과 하길래 order를 사용하지 않았습니다. 기능 동작에 문제가 없더라도, 명시적으로 작성해주는 게 좋을까요?

++postHandle이나 afterCompletion을 활용하면 좋을 것 같다고 하셨는데, postHandle이나 afterCompletion 사용해 코드가 변경되면 어차피 preHandle 이후에 호출 되니 순서 관리를 안 해도 되지 않을까?라는 생각이 들었습니다. 제가 잘못 이해한 내용이면 말씀해주세요!

2024-02-09 16:56 UTC, CMHyuk commented
preHandle에서 요청 횟수 검증 postHandle에서 요청 횟수 증가 로직을 넣으려고 했지만, postHandle은 컨트롤러 호출 후에 호출되기 때문에 증가된 요청 횟수 반환이 불가능해서 활용이 어려울 것(afterCompletion도 마찬가지)이라 생각했습니다.

그렇다고 preHandle에서 요청 횟수 증가 로직을 넣기엔, OCR API가 호출되지 않았는데 증가시킬 순 없다고 판단해서 어쩔 수 없이 validation 패키지에서 구현해야 한다고 생각했습니다.

패키지 구조에 대해 설명해주셨을 때

- presentation, application, domain이 infra를 의존하지 않는다.
- presentation → application → domain ← infrastructure

이처럼 application과 domian 패키지는 validation 패키지를 의존하면 안 되고 validation은 domain만 의존할 수 있기 때문에 ocr 구현할 때처럼 동일한 방식으로 해봤습니다. 이렇게 하면 횟수 검증 로직에 변화가 있더라도, validation 패키지만 건드리면 될 것 같은데 말씀하셨던 방향과 일치할까요?

추가적으로 궁금한 부분이 2가지가 있습니다.

1. 테스트용 컨트롤러 uri를 인터셉터에 등록했는데, 테스트를 위해서 실제 운영에서 사용되지 않는 uri를 등록해도 괜찮을까요? 등록하지 않고 테스트할 수 있는 방법을 고민해봤는데 해답이 떠오르지 않습니다.
2. 업로드 횟수를 검증하는 별도의 클래스로 분리하면 좋을 것 같다고 하셨는데, 분리했을 때와 하지 않았을 때의 큰 차이를 잘 모르겠는데 특별한 이유가 있을까요?

2024-02-10 07:03 UTC, CMHyuk commented
변경된 점
* `validation` 패키지에서 `infrastructure`로 이동
* `OcrRequestCountValidator`에서 업로드 횟수를 가져오는 로직 적절하지 않은 것 같아 분리
* 인터셉터에서 업로드 횟수 조회하고 검증 로직을 호출하는 것이 아닌 `OcrRequestCountValidator`에서 조회 + 검증 로직 합친 후 인터셉터에서 호출 하도록 수정

2024-02-10 14:58 UTC, ldk980130 requested changes
아직 좀 더 여유가 있다고 생각해서 한 번만 더 RC 드릴게요 아마 마지막일거에요..ㅎ

이젠 아키텍처는 더 안건드려도 될 것 같아요. 이것도 최선의 방법은 아니겠지만 이정도면 된 것 같습니다. 다만 메서드 네이밍이랑 로직적인 부분 등에서 수정하면 좋을 것 리뷰 남겼어요.

2024-02-10 14:58 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountProvider.java
> +}
Ocr 요청 횟수를 증가시키고 반환하는 로직을 application 하위에 두기로 결정했다면 Ocr 요층 횟수를 증가 시키는 로직 자체를 이렇게 인터페이스로 구현 안해도 될 것 같긴해요.

그리고 이 인터페이스의 구현체를 보니 `getUploadCount` 메서드 안에서 요청 횟수를 증가시키고 반환하더라구요. 이름은 get인데 데이터가 변화한다면 어색하다고 생각해요. 다른 사람이 get이라서 사용했는데 데이터가 의도치 않게 변할 수도 있구요. `increaseUploadCount`는 어떨까요?

2024-02-10 14:58 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/domain/OcrRequestHistory.java
> +    }
생성자에 의도를 담아라라는 리뷰를 이렇게 구현해주신 것 같아요! uploadCount를 굳이 파라미터로 받지 않고 아래와 같이 구현한다면 더 행동을 제약할 수 있지 않을까요?

``` java
public OcrRequestHistory(Long ownerId) {
    this.ownerId = ownerId;
    this.uploadCount = DEFAULT_UPLOAD_COUNT;
}
```

2024-02-10 14:58 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountConfig.java
> +}
> 테스트용 컨트롤러 uri를 인터셉터에 등록했는데, 테스트를 위해서 실제 운영에서 사용되지 않는 uri를 등록해도 괜찮을까요? 등록하지 않고 테스트할 수 있는 방법을 고민해봤는데 해답이 떠오르지 않습니다.

테스트 때문에 프로덕션 코드에 뭔가가 추가되는건 좋은 방향은 아닙니다. test url은 제외하는게 좋을 것 같아요. 

인터셉터의 로직을 테스트해야 하는데 테스트할 방법이 떠오르지 않는다면 인터셉터 자체는 핸들로 동작 전에 뭔가를 동작시키는 책임만 담당하게 하고 테스트 하고 싶은 로직은 별도 클래스로 분리하는 방법을 사용할 수 있어오.

그 별도 클래스를 테스트하면 로직을 테스트할 수 있을 것 같습니다.

2024-02-10 14:58 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountInterceptor.java
> +
`OcrRequestCountValidator`를 통해 요청 횟수 증가 로직을 별도 클래스로 분리하였네요! 제가 직전에 남긴 인터셉터에서 테스트하고 싶은 로직을 분리하라고 한게 바로 이 부분입니다. Validator에 대한 테스트가 존재함으로써 인터셉터 테스트를 안하더라도 좀 더 안심할 수 있게 됐다고 생각합니다.

2024-02-10 14:58 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountProviderImpl.java
> +    }
이미 남긴 리뷰지만 한 번 더 짚고 넘어가자면 `getUploadCount`는 이름만 봐서는 요처어 횟수를 '조회'하는 메서드처럼 보여요. 하지만 실제로는 데이터를 변경하고 있죠.

이렇게 데이터를 변경하는 메서드인데 get, find 등의 조회 이름을 붙여버리면 커뮤니케이션 미스가 날 수 있어요. 정말 단순히 데이터를 꺼내오는 작업에서만 get, find 등의 이름을 붙이면 좋을 것 같아요.

2024-02-10 14:58 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountValidator.java
> +                    }
5회까지는 허용 아닌가요? 4회까지 허용이고 5회가 되는 순간 예외인가요?

2024-02-11 04:33 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountValidator.java
> +                    }
**인터셉터에서 요청 횟수 검증 -> 사업자등록증 스캔 후 업로드 횟수 증가**

처음 업로드 횟수가 0이므로 요청 횟수 검증 통과 후 스캔 후 업로드 횟수 증가되어 1이 됩니다!
이처럼 반복했을 때 `>=`을 해야 5회까지 업로드가 가능해지는데, 제가 뮌가 착가했을까요?

2024-02-11 04:35 UTC, CMHyuk commented
피드백 해주신 부분 수정했습니다!

2024-02-11 05:15 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountValidator.java
> +                    }
아 이미 5회를 업로드 했으니 지금 허용하면 6회가 되버려서 예외군요. 제가 착각한 것 같습니다.

2024-02-11 05:17 UTC, ldk980130 approved these changes
수고하셨습니다!

2024-02-11 15:28 UTC, merged