[FEAT] 생일카페 찜하기 기능
BirthdayCafe/Birca_Backend pull request #51
Opened 2024-03-02 09:16 UTC by CMHyuk

## 🌍 이슈 번호
* closed #49 

## 📝 구현 내용
* 생일카페 찜, 찜 취소 기능

## 🍀 확인해야 할 부분
개선할 부분 있다면 말씀해주세요!

2024-03-02 12:18 UTC, ldk980130 requested changes
전체적으로는 잘 구현해주신 것 같습니다! 딱 2가지만 짚고 넘어가면 좋을 것 같아요!

2024-03-02 12:18 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeLikeService.java
> +    }
중복 좋아요를 했을 때 예외를 발생 시켜야할지 고민이네요. 중복 좋아요는 '방문자'는 절대 할 수 없고 프론트에서 못막았을 때만 발생해요. 이 때 좋아요에 또 좋아요를 누르는 행위에 예외를 발생시켜야 할지, 아니면 무시를 하는 방법도 있어요. 무시를 해도 전혀 문제가 안되기 때문에요. 어떤 방식을 사용하면 좋을까요?

2024-03-02 12:18 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeLikeService.java
> +    }
1. private 메서드가 static일 필요가 없을 것 같아요~

### '대관 대기' 상태이거나 '대관 취소'상태의 생일카페는 찜을 누르지 못하는 기능 구현 방법

현재 서비스 계층에서 도메인의 상태를 파악해서 예외를 던져주고 있어요. 저는 개인적으로 가능한한 로직을 도메인에게 위임하여 서비스 계층의 코드를 줄이는 것을 선호합니다.

'도메인 주도 개발 시작하기'라는 책에 다음과 같은 말이 나와요.
> 애그리거트가 갖고 있는 데이터를 이용해서 다른 애그리거트를 생성해야 한다면 애그리거트에 팩토리 메서드를 구현하는 것을 고려해 보자.

(만약 애그리거트라는 용어를 잘 모르겠다면 그냥 도메인이라 생각해주세요)

이게 무슨 말이냐 하면 코드를 아래와 같이 구성할 수도 있다는 것입니다.

``` java
    public void like(Long birthdayCafeId, LoginMember loginMember) {
        Long visitantId = loginMember.id();
        validateBirthdayCafeLikeExists(birthdayCafeId, visitantId);
        BirthdayCafe birthdayCafe = entityUtil.getEntity(BirthdayCafe.class, birthdayCafeId, BirthdayCafeErrorCode.NOT_FOUND);
        
        BirthdayCafeLike birthdayCafeLike = birthdayCafe.like(visitantId);
        birthdayCafeLikeRepository.save(birthdayCafeLike);
    }
```

이렇게 하면 `BirthdayCafe.like` 메서드는 도메인 계층이기 때문에 스프링이 필요 없는 환경에서 비즈니스 로직을 테스트할 수 있게 되는 장점도 있습니다.

물론 제가 생각한 방법이 무조건 맞다는 아닙니다. 한 번 지금 구현되어 있는 방식과 비교해서 생각을 남겨주세요!

2024-03-02 16:28 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeLikeService.java
> +    }
만약 중복 찜하기가 발생하면, 사용자가 찜한 생일 카페를 조회하면 중복된 결과가 조회될 수 있을 것이라 생각해 예외를 발생시켰습니다. 근데 생각해보니 유니크 제약 조건을 걸면 중복된 데이터가 삽입되지 않도록 데이터베이스에서 해당 작업을 처리해줘서, 굳이 또 예외를 발생시키는 로직은 필요가 없을 것 같습니다!

2024-03-02 16:28 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeLikeService.java
> +    }
이전과 비교해봤을 때, 서비스 계층의 코드가 간결해져 가독성이 좋아진 것 같습니다. 앞으론 도메인 객체에 대한 비즈니스 로직이 있으면, 해당 도메인에 작성해보도록 하겠습니다!

2024-03-03 01:12 UTC, ldk980130 approved these changes
수고하셨습니다~ 

++ 상태 변화 api 오늘 중으로 PR 날릴게요

2024-03-03 01:48 UTC, merged