[FEAT] 생일 카페 이미지 업로드 기능
BirthdayCafe/Birca_Backend pull request #67
Opened 2024-03-15 13:32 UTC by CMHyuk

## 🌍 이슈 번호
* closed #64 

## 📝 구현 내용
* 생일 카페 이미지 업로드 기능

## 🍀 확인해야 할 부분
이미지 업로드 기능은 공통적으로 쓰여서 common 패키지에 구현해봤습니다.

```
@Sql("/fixture/birthday-cafe-image-fixture.sql")
public class BirthdayCafeImageAcceptanceTest extends AcceptanceTest {

    private static final Long MEMBER_ID = 1L;
    private static final Long BIRTHDAY_CAFE_ID = 1L;

    @MockBean
    private BirthdayCafeImageFacade birthdayCafeImageFacade;

    @Test
    void 생일_카페_이미지를_저장한다() {
        //given
        File birthdayCafeImage = new File("src/test/resources/birthdayCafe.jpeg");

        // when
        ExtractableResponse<Response> response = RestAssured.given().log().all()
                .contentType(MediaType.MULTIPART_FORM_DATA_VALUE)
                .header(HttpHeaders.AUTHORIZATION, bearerTokenProvider.getToken(MEMBER_ID))
                .multiPart("images", birthdayCafeImage)
                .post("/api/v1/birthday-cafes/{birthdayCafeId}/images", BIRTHDAY_CAFE_ID)
                .then().log().all()
                .extract();

        // then
        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
    }
}
```

처음엔 이렇게 테스트 코드를 작성했는데 내부 동작이 실제로 수행되는지 확인할 수 없어 의미가 없는 테스트라고 생각했습니다.

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DatabaseIsolation
public class AcceptanceTest extends MockOAuthEnvironment {

    private static final String URL = "https://s3.ap-northeast-2.amazonaws.com/fileupload/image/example.png";

    @LocalServerPort
    private int port;

    @BeforeEach
    void setUp() {
        RestAssured.port = port;
    }

    @Autowired
    protected TestBearerTokenProvider bearerTokenProvider;

    @MockBean
    private AmazonS3 amazonS3;

    @BeforeEach
    void mockAwsS3() throws MalformedURLException {
        given(amazonS3.putObject(any(PutObjectRequest.class)))
                .willReturn(new PutObjectResult());
        given(amazonS3.getUrl(any(), any()))
                .willReturn(new URL(URL));
    }
}
```
이렇게 AmazonS3 목 객체 주입 후 인수 테스트에서 아래 로직을 제거했습니다.
```
@MockBean
private BirthdayCafeImageFacade birthdayCafeImageFacade;
```
이렇게 하면 내부 동작이 실제로 수행되는지 확인이 가능한데 AcceptanceTest에 저 로직을 넣는 게 적절한지 의문이 들었습니다. 처음엔 MockOAuthEnvironment에 합쳐볼까 했지만, 앞으로 이미지 업로드를 구현할 때 S3에 저장하는 로직 + db에 저장하는 로직 둘로 나누면 AmazonS3를 모킹하는 건 서비스 테스트에서는 사용하지 않고 인수 테스트에서만 사용할 것 같다고 생각했습니다. 제가 구현한 방식 외에 더 좋은 방법이 있을까요?

혹시 제 설명이 잘못됐거나 미흡한 부분이 있으면 말씀해주세요 !

2024-03-15 15:23 UTC, ldk980130 requested changes
> 앞으로 이미지 업로드를 구현할 때 S3에 저장하는 로직 + db에 저장하는 로직 둘로 나누면 AmazonS3를 모킹하는 건 서비스 테스트에서는 사용하지 않고 인수 테스트에서만 사용할 것 같다고 생각했습니다. 제가 구현한 방식 외에 더 좋은 방법이 있을까요?

외부 인프라를 인터페이스로 분리하고 테스트에선 모킹처리하는 건 일반적이고 좋은 방법입니다. 다만 아래 코멘트에도 남겼지만 `ImageUploader`를 모킹하는 것과 `AmazonS3`를 모킹하는 것 중에 어떤 것을 모킹하는게 나을지 생각해보면 좋을 것 같아요.

그리고 `Facade`에 대한 테스트도 작성한다면 해당 모킹을 서비스 테스트에서도 사용할 수 있지 않을까요?

2024-03-15 15:23 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacade.java
> +    }
최대 10장을 업로드할 수 있으니 아래 코드로는 S3와 네트워크 통신이 최대 10번이 이루어지는 걸까요? 혹시 한 번에 업로드할 수 있는 방법은 없는걸까요? 없다면 어쩔 수 없겠지만 성능이 살짝 걱정되네요.
``` java
        List<String> imagesUrl = images.stream()
                .map(imageUploader::upload)
                .toList();
``` 

++ 그리고 Facade에 대한 테스트는 없던데 작성하지 않은 이유가 있을까요?

2024-03-15 15:23 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageValidator.java
> +        }
요청이 최대 몇 개인지도 봐야겠지만 기존에 이 생일 카페에 저장된 사진 개수랑 합쳤을 때도 10장이 넘으면 안되지 않을까요?

2024-03-15 15:23 UTC, ldk980130 commented on src/test/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageValidatorTest.java
> +}
1. 기존에 저장된 이미지와 합쳐서 10개가 되는지 판단하도록 테스트를 작성해주세요.
2. 파일 끝에 개행 추가해주세요

2024-03-15 15:23 UTC, ldk980130 commented on src/test/java/com/birca/bircabackend/support/enviroment/AcceptanceTest.java
> +    }
`ImageUploader`를 목 처리할 수도 있고, `amazonS3`를 목 처리하는 방법이 있는데 `amazonS3`를 목처리 하신 이유가 있을까요?

2024-03-15 15:29 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/common/upload/AwsS3Uploader.java
> +        }
S3와의 통신에서 뭔가 문제가 발생했을 때 인터널 서버 에러 발생시키는 것 좋습니다! 근데 추가적으로 로그를 남기면 나중에 문제를 파악할 때 더 도움이 될 것 같아요.
``` java
log.error(...)
```

2024-03-15 16:44 UTC, CMHyuk commented on src/test/java/com/birca/bircabackend/support/enviroment/AcceptanceTest.java
> +    }
아 ImageUploader를 목 처리하는 게 더 좋을 것 같네요 !

2024-03-15 16:47 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacade.java
> +    }
찾아봤는데 한 번에 업로드할 수 있는 방법은 찾지 못했습니다. 조금 더 알아볼게요 ~

2024-03-15 16:47 UTC, CMHyuk commented
피드백 해주신 부분 수정했는데, 제대로 했는지 확인해주시면 감사하겠습니다 !

2024-03-16 03:50 UTC, ldk980130 commented on src/test/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacadeTest.java
> +}
facade 내부에서 mockito를 사용했으면 해당 목 객체가 호출 되었는지, 정확히 몇 번 호출되었는지도 검증하는 방법이 있어요. 한 번 확인해보면 어떨까요?

2024-03-16 07:00 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/common/upload/AwsS3Uploader.java
> +    private static final ObjectMetadata OBJECT_METADATA = new ObjectMetadata();
이미지 파일마다 `ObjectMetadata`의 `content-length` 내용이 달라지는데 전역 상태로 관리하는 이유가 있나요? 동시성 문제가 생기진 않을까요?

2024-03-16 07:57 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/common/upload/AwsS3Uploader.java
> +    private static final ObjectMetadata OBJECT_METADATA = new ObjectMetadata();
앗 동시성은 고려하지 못했네요 수정하겠습니다!

2024-03-16 08:20 UTC, CMHyuk commented
말씀해주신 부분 반영했습니다.
근데 인수 테스트와 서비스 테스트에서 모두 사용하고자 `MockEnvironment`에 목 관련 코드를 다 넣었는데 좋은 방법일까요? 아니면 더 좋은 구조가 있을까요? 만약 또 여러 테스트에서 공통적으로 사용될 새로운 목 객체가 필요하면 `MockEnvironment`가 지저분해지지 않을까라는 생각이 들었습니다.

2024-03-16 09:24 UTC, ldk980130 reviewed
@CMHyuk 

> 근데 인수 테스트와 서비스 테스트에서 공통적으로 사용되는 목 코드를 MockEnvironment에 다 넣었는데 좋은 방법일까요? 아니면 더 좋은 구조가 있을까요? 만약 또 여러 테스트에서 공통적으로 사용될 새로운 목 객체가 필요하면 MockEnvironment가 지저분해지지 않을까라는 생각이 들었습니다.

`MockEnvironment`으로 공통적으로 관리한 것 괜찮은 것 같습니다. 외부 인프라 서비스가 많아지면 해당 클래스가 길어질 수도 있지만 그렇다고 각 테스트에서 별도로 `MockBean`을 정의하게 되면 애플리케이션 컨텍스트를 캐싱하지 못하고 별도로 생성되어 테스트 속도가 훗날 느려질 수가 있어요.

> 전체 테스트 실행 시 사용하는 빈 구성이 다르면 애플리케이션 컨텍스트를 새로 생성합니다.

스프링 컨테이너를 최소로 띄우면서 테스트를 진행하려면 똑같은 빈 구성으로 통합 테스트들을 구성하면 좋을 것 같아요. 그리고 목 처리할 외부 인프라가 얼마나 늘어날진 모르지만 당장은 괜찮은 것 같습니다~

2024-03-16 16:19 UTC, CMHyuk commented
다중 이미지 업로드 -> 단일 이미지 업로드로 수정했습니다! 제가 놓친 부분 있는지 확인해주시면 좋을 것 같아요 ~

2024-03-17 01:26 UTC, ldk980130 approved these changes
수고하셨습니다~ 대표 이미지와 기본 이미지 개수 제한을 각각 1개, 10개로만 수정하고 머지하면 될 것 같아요

2024-03-17 01:51 UTC, merged