[FEAT] 생일 카페 대표 이미지 지정
BirthdayCafe/Birca_Backend pull request #71
Opened 2024-03-18 12:55 UTC by CMHyuk

## 🌍 이슈 번호
* closed #70 

## 📝 구현 내용
* 생일 카페 대표 이미지 지정 

## 🍀 확인해야 할 부분
대표 이미지 조회
존재 → S3에 새로운 대표 이미지 저장 → db 파일명 업데이트 → 기존 S3에 저장된 대표이미지 삭제
존재 x → S3와 DB에 새로 저장
제가 구현한 방식 외에 더 좋은 방식이나 잘못된 로직이 있다면 말씀해주세요 !

    @Override
    public void delete(String imageUrl) {
        amazonS3.deleteObject(new DeleteObjectRequest(bucket, getKey(imageUrl)));
    }

    private String getKey(String imageUrl) {
        String key = imageUrl.replaceAll(DEFAULT_PATH, "");
        return URLDecoder.decode(key, StandardCharsets.UTF_8);
    }
이미지 파일명이 한글이면 S3엔 한글이 깨지지 않고 저장이 되는데, 조회할 때는 한글 깨짐 현상이 있습니다. 그냥 삭제하면 삭제가 안돼서 디코딩 후 삭제하도록 했습니다.

2024-03-18 13:45 UTC, ldk980130 requested changes
수고하셨습니다! 크게 구조적으로 변경할 부분은 없고 짜잘하게 확인해주시면 좋을 것 같아요~

++ 한글 깨지는 현상은 해결이 안되는 걸까요? 방법을 찾아보고 해결하면 좋을 것 같습니다.

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacade.java
> +    }
기본 이미지 저장 메서드 이름이 `update`인 이유가 있을까요?

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacade.java
> +                .ifPresent(imageUploader::delete);
`BirthdayCafeImageService`의 `updateMainImage` 메서드가 메인 이미지를 저장하고, 만약 기존 메인 이미지가 있다면 그 url을 반환하네요.

메인 이미지를 수정하는 메서드에서 기존 url을 반환하는게 살짝 어색하게 느껴지긴 하지만 이 방법이 최선일 것 같긴 해요. 일단 이대로 갑시다

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +                    mainImage.updateMainImage(imageUrl);
수정하는건 url이니까 메서드 이름으로 `updateUrl`은 어떨까요?

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +                    return Optional.ofNullable(previousImageUrl);
`ofNullable`은 코드를 작성하는 개발자도 내부가 `null`일지 아닐지 모르는 경우에 주로 사용합니다.

이렇게 값이 무조건 있는 경우는 `of`를 사용하면 좋을 것 같아요!

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/domain/BirthdayCafeImage.java
> +    }
가독성 👍

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/common/upload/AwsS3Uploader.java
> +
이건 하드코딩 할게 아니라 yml로 분리해야 하지 않을까요?

2024-03-18 13:45 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +                .stream()
`findByBirthdayCafeIdAndIsMain` 메서드에서 true로 값을 뽑을 경우 '메인 이미지를 조회한다'라는 의미가 되는데 반환이 `List`일 필요가 있을까요? 메인 이미지는 단 하나 뿐인데 말이죠.

아래의 두 메서드로 분리하면 어떨까요?
``` java
List<BirthdayCafeImage> findDefaultByBirthdayCafeId(...);
Optional<BirthdayCafeImage> findMainByBirthdayCafeId(...);
```

2024-03-18 14:41 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/common/upload/AwsS3Uploader.java
> +
앗 넵 수정하겠습니다 ~

2024-03-18 14:42 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacade.java
> +    }
``saveDefaultImage``가 좋을 것 같네요. 대표 이미지 지정을 구현하면서 잠시 혼동이 온 것 같습니다.

2024-03-18 14:42 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +                    return Optional.ofNullable(previousImageUrl);
> ofNullable은 코드를 작성하는 개발자도 내부가 null일지 아닐지 모르는 경우에 주로 사용합니다.

오 넵 알겠습니다 ~

2024-03-18 14:43 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +                .stream()
아 그렇네요 이 생각을 못 했네요 ~ 수정해보도록 할게요 !

2024-03-18 15:10 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/domain/BirthdayCafeImageRepository.java
> +    Optional<BirthdayCafeImage> findMainByBirthdayCafeIdAndIsMain(Long birthdayCafeId, Boolean isMain);
메서드 이름의 isMain 값이 뭔지 결정이 되어 있으니 isMain은 파라미터로 받지 말고 쿼리로 지정해버려도 되지 않을까요?

`@Query("... where bci.isMain = true")`

2024-03-18 15:23 UTC, CMHyuk commented
> 한글 깨지는 현상은 해결이 안되는 걸까요? 방법을 찾아보고 해결하면 좋을 것 같습니다.

```UUID.randomUUID() + "-" + image.getOriginalFilename();```
S3에 저장할 때 파일 이름을 이용하는 것이 아닌

```UUID.randomUUID() + "-" + LocalDateTime.now().format(ofPattern("yyyyMMddHHmmss"));```
이 조합으로 저장해 애초에 한글로 저장되는 일이 없도록 수정했는데, 문제 생길 경우가 있을지 확인해주시면 좋을 것 같아요 ~

2024-03-19 02:39 UTC, ldk980130 approved these changes
수고하셨습니다~

S3에 올리는 이미지 이름은 생각해보면 딱히 의미가 없어도 될 것 같아요. UUID + 날짜 정보도 괜찮다고 생각합니다.

2024-03-19 05:31 UTC, merged