[FEAT] 생일 카페 이미지 삭제
BirthdayCafe/Birca_Backend pull request #74
Opened 2024-03-19 11:44 UTC by CMHyuk

## 🌍 이슈 번호
* closed #73 

## 📝 구현 내용
* 생일 카페 이미지 삭제

## 🍀 확인해야 할 부분
현재 생일 카페 이미지 url에 공통적으로 ```images```가 들어갑니다. 다중 이미지 처리 -> 단건 이미지 처리로 바뀌었는데, ```image```로 변경하는 게 더 적절할까요? 아니면 굳이 변경할 필요가 없을까요?

2024-03-19 13:44 UTC, ldk980130 requested changes
수고하셨습니다. 간단하게 코멘트 남긴거 확인해주세요!

url의 images는 복수의 의미라기 보단 api 설계에서 복수형을 보통 사용하기 때문에 쓴거라 그대로 둬도 된 것 같아요.

2024-03-19 13:44 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageFacade.java
> +    }
Facade에서 S3 통신과 DB 통신이 원자적으로 이루어지지 않아요.

이미지를 업로드할 때는 DB에 저장할 url을 s3로부터 받아와야 하기에 업로드가 먼저 일어나야 해요.그리고 업로드를 하고 db 저장에 실패하더라도 s3에 db에 매핑 안된 데이터가 남을 뿐 사용자는 다시 이미지를 업로드하면 됩니다.

하지만 삭제의 경우는 어떨까요? 만약 s3에 삭제 요청이 이루어진 뒤 db 삭제에 실패한다면 어떻게 될까요?

2024-03-19 13:44 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +    }
url만으로도 유니크하기에 삭제가 될 것 같은데 birthdayCafeId도 함께 추가하는 이유가 있을까요?

아니면 아예 BirthdayCafeImage를 조회하고 엔티티를 delete하는 방법도 있을 것 같아요. 조회하면서 존재하는 이미지인가를 검증할 수도 있구요.

2024-03-19 13:44 UTC, ldk980130 commented on src/test/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageServiceTest.java
> +    }
개수를 확인하는 것도 좋지만 "image1.com"이라는 url이 존재하지 않는 걸 확인하면 더 정확하지 않을까요?

2024-03-20 08:06 UTC, CMHyuk commented
url만으로 삭제하도록 했습니다. 만약 존재하지 않는 url을 삭제하려 해도 예외가 발생하지 않고, 요청이 무시가 됩니다.

> BirthdayCafeImage를 조회하고 엔티티를 delete하는 방법도 있을 것 같아요. 조회하면서 존재하는 이미지인가를 검증

 존재 유무를 검증하지 않고, 제가 구현한대로 하면 문제될 상황이 있을까요?

2024-03-20 08:07 UTC, CMHyuk commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +    }
url만으로 삭제하도록 했습니다. 만약 존재하지 않는 url을 삭제하려 해도 예외가 발생하지 않고, 요청이 무시가 됩니다.

> BirthdayCafeImage를 조회하고 엔티티를 delete하는 방법도 있을 것 같아요. 조회하면서 존재하는 이미지인가를 검증

존재 유무를 검증하지 않고, 제가 구현한대로 하면 문제될 상황이 있을까요?

2024-03-20 13:48 UTC, ldk980130 commented on src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeImageService.java
> +    }
딱히 문제될 건 없어 보이네요 이렇게 구현해도 될 것 같습니다.

2024-03-20 13:48 UTC, ldk980130 approved these changes
수고하셨습니다~

2024-03-20 13:55 UTC, merged